### ISSUE TITLE
can't change wrong size of window 

### ISSUE THREAD

**Issue by Jeremi360** [radoveev/pyprinciple#4]
When I run this app I got window like this and I can't resize.
![wrong_window_size](https://user-images.githubusercontent.com/1294815/31309075-b45e25e4-ab80-11e7-878a-15efc22a8946.png)

**Comment by radoveev** [comment]
Yes, I'm almost sure the reason for this is that the progress bars in the students tab of the school management screen take up too much vertical space. I need to change the style of progress bars in appstyle.qss (the application-wide style sheet) so that they use less vertical space.

**Comment by radoveev** [comment]
As of now the current minimum vertical window size is a bit below 700px. If your screen resolution is smaller than that, for example 800x600, you will not be able to display the complete window. We could reduce the minium size requirements of the game window further by adding scrollbars to some widgets. Feel free to open a pull request about it if you want to work on that :-)
